# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='confirm_password',
            field=models.CharField(default=b'', max_length=40),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(default=b'', max_length=254),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(default=b'', max_length=40),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(default=b'', max_length=120),
        ),
    ]
