# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170720_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='updated_on',
        ),
    ]
