# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_sessiontoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(default=b'', max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('company_registration_no', models.CharField(max_length=30)),
                ('status_of_applicant', models.CharField(max_length=40)),
                ('nature_of_organization', models.CharField(max_length=50)),
                ('nature_of_business', models.CharField(max_length=50)),
                ('experience', models.IntegerField(default=0)),
                ('pan_no', models.IntegerField(default=0)),
                ('tin_no', models.IntegerField(default=0)),
                ('aadhar_no', models.IntegerField(default=0)),
                ('turnover', models.IntegerField(default=0)),
                ('net_worth', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='sessiontoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Signup'),
        ),
    ]
