# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20170722_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Signup'),
        ),
    ]
