# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170722_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_no', models.CharField(max_length=20)),
                ('tender_type', models.CharField(max_length=30)),
                ('form_of_contact', models.CharField(max_length=30)),
                ('tender_category', models.CharField(max_length=20)),
                ('work_item_title', models.CharField(max_length=50)),
                ('work_description', models.CharField(max_length=200)),
                ('pre_qual_details', models.CharField(max_length=200)),
                ('product_category', models.CharField(max_length=50)),
                ('product_sub_category', models.CharField(max_length=100)),
                ('contract_type', models.CharField(max_length=50)),
                ('bid_valid_day', models.IntegerField(default=0)),
                ('completion_period', models.IntegerField(default=0)),
                ('locations', models.CharField(max_length=40)),
                ('pincode', models.IntegerField(default=0)),
                ('publishing_date', models.DateField()),
                ('document_sale_start', models.DateTimeField()),
                ('document_sale_end', models.DateTimeField()),
                ('seek_clarification_start', models.DateTimeField()),
                ('seek_clarification_end', models.DateTimeField()),
                ('pre_bid_meeting', models.DateTimeField()),
                ('bid_submission_start', models.DateTimeField()),
                ('bid_submission_end', models.DateTimeField()),
                ('bid_opening_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='sessiontoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Signup'),
        ),
    ]
